### PR TITLE
Rename demo file name

### LINKED ISSUE #431: Build demo Docker image failed
```bash
Sending build context to Docker daemon  7.392MB
Step 1/6 : FROM tatsushid/tinycore-python:2.7
 ---> da605b5a5fc5
Step 2/6 : RUN pip install visualdl
 ---> Using cache
 ---> e3501944165c
Step 3/6 : WORKDIR /
 ---> Using cache
 ---> 23abec58902e
Step 4/6 : COPY ./demo/vdl_scratch.py vdl_scratch.py
lstat demo/vdl_scratch.py: no such file or directory
```

### PR DESCRIPTION
**Pull request by Yancey0623**
Fixed #431

### CODE REVIEW

**Comment by daming-lu** [comment]
Lots of [places](https://github.com/PaddlePaddle/VisualDL/search?utf8=%E2%9C%93&q=vdl_create_scratch_log&type=) refer this file. My understanding is that the command only works for macOS but not Ubuntu Docker, right?

**Comment by nickyfantasy** [comment]
I think we should fix the script in Dockerfile.demo instead

Btw, [Dockerfile.demo](https://github.com/PaddlePaddle/VisualDL/blob/develop/Dockerfile.demo) seems pretty old, @daming-lu, I think you have a docker image with all DL framework installed right? Can you update that?

**Comment by jetfuel** [comment]
Fixed by https://github.com/PaddlePaddle/VisualDL/pull/438

**Comment by daming-lu** [comment]
fixed [here](https://github.com/PaddlePaddle/VisualDL/pull/438)

**Pull request closed without merging**
