### PR TITLE
Should build test under release mode as well.

### PR DESCRIPTION
**Pull request by jetfuel**
https://github.com/PaddlePaddle/VisualDL/issues/213

### CODE REVIEW

**Comment by cs2be** [comment]
LGTM, please resolve build conflicts

**Comment by jetfuel** [comment]
Ah, the GLOG library is included only in Release Mode. That's why the build failed.

**Comment by Superjomn** [comment]
Release mode should just use the simple `CHECK` defined in `logging.h`, not GLOG (so no need to link GLOG). 

GLOG will `exit` the process, the simple `CHECK` just yield an exception, and in release mode, to avoid Flask server process terminate, the simple `CHECK` should be used instead.

**Comment by jetfuel** [comment]
We shouldn't build the test that requires GLOG in Release. GLOG might exit the Flask. 
Going to close this PR.

**Pull request closed without merging**
